add_ace group.superadmin easyadmin.player.kick allow
add_ace group.superadmin easyadmin.player.spectate allow
add_ace group.superadmin easyadmin.player.teleport allow
add_ace group.superadmin easyadmin.player.slap deny
add_ace group.superadmin easyadmin.player.freeze allow
add_ace group.superadmin easyadmin.player.revive allow
add_ace group.superadmin easyadmin.player.kick allow
add_ace group.superadmin easyadmin.player.spectate allow
add_ace group.superadmin easyadmin.player.teleport allow
add_ace group.superadmin easyadmin.player.freeze allow
add_ace group.superadmin easyadmin.player.revive allow
add_ace group.superadmin easyadmin.player.ban.temporary	allow
add_ace group.superadmin easyadmin.player.ban.permanent allow
add_ace group.superadmin easyadmin.player.unban allow
add_ace group.superadmin easyadmin.player.teleport.single allow
add_ace group.superadmin easyadmin.player.teleport.everyone allow
add_ace group.superadmin easyadmin.player.reports.view allow
add_ace group.superadmin easyadmin.player.reports.process allow
add_ace group.superadmin easyadmin..server.permissions.read allow
add_ace group.superadmin easyadmin.server.cleanup.props allow
add_ace group.superadmin easyadmin.player.slap deny
add_ace group.superadmin easyadmin.immune allow
add_ace group.superadmin easyadmin.player.adminjail allow